frase = input('Digite uma frase:')
frase = frase.upper()
contador = frase.count('A')
acharprimeiro = frase.find('A')
acharultimo = frase.rfind('A')
print(contador)
print(acharprimeiro)
print(acharultimo)